plugin: constructed
strict: false

groups:
  kube_control_plane: "'k8s' in inventory_hostname"
  etcd: "'k8s' in inventory_hostname"
  kube_node: "'k8s' in inventory_hostname"

compose:
  ansible_user: "'root'"
  ansible_password: "'onejobplease'"
  ansible_host: >-
    "vm/" + inventory_hostname.replace('default-', '')